### ISSUE TITLE
Firefox: conflitto tra draggable jquery e mouseup

### ISSUE THREAD

**Issue by JSalvo** [OADplus/MappaConcettuale#1]
Riferimento: node.js

La funzione che gestisce l'evento mouseup, richiama il metodo stopPropagation. In Firefox, tale metodo, impedisce la conclusione dell'evento di drag. Ciò non avviene in Google Chrome.

**Comment by Rexios** [comment]
Grande JSalvo. Oggi ci guardiamo.

**Comment by JSalvo** [comment]
Problema risolto. Modificato node.js
